version: '3'

services:
  db:
    image: postgres:latest
    container_name: my-db5
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}